HW 05 - Completed the test methods, the call of the test delete() method causes an assertion error and the assertion of the AbstractArrayStorageTest class causes:
org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.urise.webapp.storage.AbstractArrayStorageTest':
  1. Test class should have exactly one public constructor